// <auto-generated />
using EmployeeScheduler.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeScheduler.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    partial class ScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeScheduler.Models.Days", b =>
                {
                    b.Property<int>("DaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DaysId");

                    b.ToTable("days");

                    b.HasData(
                        new
                        {
                            DaysId = 1,
                            Name = "Monday"
                        },
                        new
                        {
                            DaysId = 2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            DaysId = 3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            DaysId = 4,
                            Name = "Thursday"
                        },
                        new
                        {
                            DaysId = 5,
                            Name = "Friday"
                        },
                        new
                        {
                            DaysId = 6,
                            Name = "Saturday"
                        },
                        new
                        {
                            DaysId = 7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("EmployeeScheduler.Models.Shifts", b =>
                {
                    b.Property<int>("ShiftsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DaysId")
                        .HasColumnType("int");

                    b.Property<int>("EndingHour")
                        .HasColumnType("int");

                    b.Property<int>("StartingHour")
                        .HasColumnType("int");

                    b.Property<int>("UserLogonId")
                        .HasColumnType("int");

                    b.HasKey("ShiftsID");

                    b.HasIndex("DaysId");

                    b.HasIndex("UserLogonId");

                    b.ToTable("shifts");
                });

            modelBuilder.Entity("EmployeeScheduler.Models.UserLogon", b =>
                {
                    b.Property<int>("UserLogonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserLogonId");

                    b.ToTable("userLogons");

                    b.HasData(
                        new
                        {
                            UserLogonId = 1,
                            FirstName = "Bilal",
                            LastName = "Hodzic"
                        },
                        new
                        {
                            UserLogonId = 2,
                            FirstName = "Noah",
                            LastName = "Arterburn"
                        },
                        new
                        {
                            UserLogonId = 3,
                            FirstName = "Gage",
                            LastName = "Payton"
                        });
                });

            modelBuilder.Entity("EmployeeScheduler.Models.Shifts", b =>
                {
                    b.HasOne("EmployeeScheduler.Models.Days", "Days")
                        .WithMany("shifts")
                        .HasForeignKey("DaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeScheduler.Models.UserLogon", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserLogonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Days");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmployeeScheduler.Models.Days", b =>
                {
                    b.Navigation("shifts");
                });

            modelBuilder.Entity("EmployeeScheduler.Models.UserLogon", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
